export const easyQuestions = [
  {
    id: 1,
    question: 'What is the national flower of Pakistan?',
    options: ['Rose', 'Sunflower', 'Jasmine', 'Tulip'],
    correctAnswer: 'Jasmine',
  },
  {
    id: 2,
    question: 'What was the real name of Quaid-e-Azam?',
    options: [
      'Liaquat Ali Khan',
      'Muhammad Ali Jinnah',
      'Allama Iqbal',
      'Sir Syed Ahmed Khan',
    ],
    correctAnswer: 'Muhammad Ali Jinnah',
  },
  {
    id: 3,
    question: 'Which is the largest ocean in the world?',
    options: [
      'Arctic Ocean',
      'Atlantic Ocean',
      'Indian Ocean',
      'Pacific Ocean',
    ],
    correctAnswer: 'Pacific Ocean',
  },
  {
    id: 4,
    question: 'When did Pakistan gain independence?',
    options: ['1945', '1946', '1947', '1948'],
    correctAnswer: '1947',
  },
  {
    id: 5,
    question: 'Who is a famous Urdu poet?',
    options: [
      'Allama Iqbal',
      'Mirza Ghalib',
      'Faiz Ahmed Faiz',
      'All of the above',
    ],
    correctAnswer: 'All of the above',
  },
  {
    id: 6,
    question: 'What is the longest river in the world?',
    options: ['Nile', 'Amazon', 'Indus', 'Ganges'],
    correctAnswer: 'Nile',
  },
  {
    id: 7,
    question: 'What is the national sport of Pakistan?',
    options: ['Cricket', 'Hockey', 'Football', 'Kabaddi'],
    correctAnswer: 'Hockey',
  },
  {
    id: 8,
    question: 'What is “Apple” famous for?',
    options: ['Mobile Phones', 'Fruits', 'Laptops', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 9,
    question: 'What is the highest mountain in the world?',
    options: ['K2', 'Mount Everest', 'Kilimanjaro', 'Nanga Parbat'],
    correctAnswer: 'Mount Everest',
  },
  {
    id: 10,
    question: 'What is the national animal of Pakistan?',
    options: ['Tiger', 'Markhor', 'Elephant', 'Lion'],
    correctAnswer: 'Markhor',
  },
  {
    id: 11,
    question: 'What is the “Brain” of a computer called?',
    options: ['Mouse', 'CPU', 'Monitor', 'Keyboard'],
    correctAnswer: 'CPU',
  },
  {
    id: 12,
    question: 'How many surahs are in the Quran?',
    options: ['110', '114', '120', '125'],
    correctAnswer: '114',
  },
  {
    id: 13,
    question: 'What is the first Kalima of Islam?',
    options: [
      'Kalima-e-Tayyaba',
      'Kalima-e-Shahadat',
      'Kalima-e-Tauheed',
      'Kalima-e-Astaghfar',
    ],
    correctAnswer: 'Kalima-e-Tayyaba',
  },
  {
    id: 14,
    question: 'Which is the largest country in the world by area?',
    options: ['China', 'Russia', 'Canada', 'USA'],
    correctAnswer: 'Russia',
  },
  {
    id: 15,
    question: 'What is the largest city in Pakistan?',
    options: ['Lahore', 'Karachi', 'Islamabad', 'Peshawar'],
    correctAnswer: 'Karachi',
  },
  {
    id: 16,
    question: 'Where is the Eiffel Tower located?',
    options: ['London', 'Paris', 'New York', 'Rome'],
    correctAnswer: 'Paris',
  },
  {
    id: 17,
    question: 'What is the currency of Pakistan?',
    options: ['Dollar', 'Rupee', 'Taka', 'Riyal'],
    correctAnswer: 'Rupee',
  },
  {
    id: 18,
    question: 'Which is the largest desert in the world?',
    options: [
      'Gobi Desert',
      'Sahara Desert',
      'Arabian Desert',
      'Atacama Desert',
    ],
    correctAnswer: 'Sahara Desert',
  },
  {
    id: 19,
    question: 'Who is the founder of Facebook?',
    options: ['Bill Gates', 'Steve Jobs', 'Mark Zuckerberg', 'Elon Musk'],
    correctAnswer: 'Mark Zuckerberg',
  },
  {
    id: 20,
    question: 'Which river flows near Lahore?',
    options: ['Ravi', 'Sindh', 'Jhelum', 'Chenab'],
    correctAnswer: 'Ravi',
  },
  {
    id: 21,
    question: 'Which country is known as the “Land of the Rising Sun”?',
    options: ['China', 'Japan', 'South Korea', 'Thailand'],
    correctAnswer: 'Japan',
  },
  {
    id: 22,
    question: 'How many continents are there?',
    options: ['5', '6', '7', '8'],
    correctAnswer: '7',
  },
  {
    id: 23,
    question: 'What is the national language of Pakistan?',
    options: ['English', 'Punjabi', 'Sindhi', 'Urdu'],
    correctAnswer: 'Urdu',
  },
  {
    id: 24,
    question: 'Who invented the light bulb?',
    options: [
      'Nikola Tesla',
      'Thomas Edison',
      'Alexander Graham Bell',
      'Isaac Newton',
    ],
    correctAnswer: 'Thomas Edison',
  },
  {
    id: 25,
    question: 'What is the capital city of Pakistan?',
    options: ['Lahore', 'Karachi', 'Islamabad', 'Peshawar'],
    correctAnswer: 'Islamabad',
  },
  {
    id: 26,
    question: 'What is the smallest planet in our solar system?',
    options: ['Earth', 'Mars', 'Mercury', 'Venus'],
    correctAnswer: 'Mercury',
  },
  {
    id: 27,
    question: 'What is the boiling point of water?',
    options: ['90°C', '100°C', '110°C', '120°C'],
    correctAnswer: '100°C',
  },
  {
    id: 28,
    question: 'Which organ pumps blood in the human body?',
    options: ['Lungs', 'Brain', 'Heart', 'Kidney'],
    correctAnswer: 'Heart',
  },
  {
    id: 29,
    question: 'What is the national bird of Pakistan?',
    options: ['Peacock', 'Chukar', 'Crow', 'Parrot'],
    correctAnswer: 'Chukar',
  },
  {
    id: 30,
    question: 'How many sides does a triangle have?',
    options: ['2', '3', '4', '5'],
    correctAnswer: '3',
  },
  {
    id: 31,
    question: 'Which planet is known as the Red Planet?',
    options: ['Earth', 'Mars', 'Venus', 'Jupiter'],
    correctAnswer: 'Mars',
  },
  {
    id: 32,
    question: 'What is the name of Pakistan’s national poet?',
    options: ['Faiz Ahmed Faiz', 'Mirza Ghalib', 'Allama Iqbal', 'Nasir Kazmi'],
    correctAnswer: 'Allama Iqbal',
  },
  {
    id: 33,
    question: 'What is the hardest natural substance on Earth?',
    options: ['Gold', 'Iron', 'Diamond', 'Platinum'],
    correctAnswer: 'Diamond',
  },
  {
    id: 34,
    question: 'How many colors are in the rainbow?',
    options: ['5', '6', '7', '8'],
    correctAnswer: '7',
  },
  {
    id: 35,
    question: 'Which country is famous for pizza?',
    options: ['France', 'Italy', 'Germany', 'Spain'],
    correctAnswer: 'Italy',
  },
  {
    id: 36,
    question: 'What is the chemical symbol for water?',
    options: ['O2', 'H2O', 'CO2', 'NaCl'],
    correctAnswer: 'H2O',
  },
  {
    id: 37,
    question: 'Which animal is known as the King of the Jungle?',
    options: ['Tiger', 'Lion', 'Elephant', 'Leopard'],
    correctAnswer: 'Lion',
  },
  {
    id: 38,
    question: 'What is the official religion of Pakistan?',
    options: ['Hinduism', 'Christianity', 'Islam', 'Judaism'],
    correctAnswer: 'Islam',
  },
  {
    id: 39,
    question: 'How many letters are in the English alphabet?',
    options: ['24', '25', '26', '27'],
    correctAnswer: '26',
  },
  {
    id: 40,
    question: 'Which planet is closest to the Sun?',
    options: ['Mercury', 'Venus', 'Earth', 'Mars'],
    correctAnswer: 'Mercury',
  },
  {
    id: 41,
    question: 'What do bees produce?',
    options: ['Wax', 'Honey', 'Pollen', 'Nectar'],
    correctAnswer: 'Honey',
  },
  {
    id: 42,
    question: 'Which city is known as the City of Lights in Pakistan?',
    options: ['Karachi', 'Lahore', 'Islamabad', 'Peshawar'],
    correctAnswer: 'Karachi',
  },
  {
    id: 43,
    question: 'What is the shape of a football?',
    options: ['Circle', 'Oval', 'Square', 'Hexagonal'],
    correctAnswer: 'Circle',
  },
  {
    id: 44,
    question: 'What is the study of stars and planets called?',
    options: ['Biology', 'Geology', 'Astronomy', 'Astrology'],
    correctAnswer: 'Astronomy',
  },
  {
    id: 45,
    question: 'What is the capital city of France?',
    options: ['London', 'Berlin', 'Rome', 'Paris'],
    correctAnswer: 'Paris',
  },
  {
    id: 46,
    question: 'What is the national tree of Pakistan?',
    options: ['Oak', 'Deodar', 'Pine', 'Banyan'],
    correctAnswer: 'Deodar',
  },
  {
    id: 47,
    question: 'Which continent is the Sahara Desert located in?',
    options: ['Asia', 'Africa', 'Europe', 'Australia'],
    correctAnswer: 'Africa',
  },
  {
    id: 48,
    question: 'How many days are in a leap year?',
    options: ['364', '365', '366', '367'],
    correctAnswer: '366',
  },
  {
    id: 49,
    question: 'Which organ is responsible for breathing?',
    options: ['Heart', 'Lungs', 'Kidney', 'Liver'],
    correctAnswer: 'Lungs',
  },
  {
    id: 50,
    question: 'What is the largest mammal on Earth?',
    options: ['Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus'],
    correctAnswer: 'Blue Whale',
  },
];

export const normalQuestions = [
  {
    id: 1,
    question: 'Which country is known as the Land of the Rising Sun?',
    options: ['China', 'Japan', 'Thailand', 'South Korea'],
    correctAnswer: 'Japan',
  },
  {
    id: 2,
    question: 'Who is the author of the famous book "A Brief History of Time"?',
    options: [
      'Albert Einstein',
      'Isaac Newton',
      'Stephen Hawking',
      'Galileo Galilei',
    ],
    correctAnswer: 'Stephen Hawking',
  },
  {
    id: 3,
    question: 'Which is the smallest country in the world by area?',
    options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
    correctAnswer: 'Vatican City',
  },
  {
    id: 4,
    question: 'What is the chemical symbol for gold?',
    options: ['Go', 'Au', 'Ag', 'Gd'],
    correctAnswer: 'Au',
  },
  {
    id: 5,
    question: 'Who discovered penicillin?',
    options: [
      'Alexander Fleming',
      'Louis Pasteur',
      'Marie Curie',
      'Edward Jenner',
    ],
    correctAnswer: 'Alexander Fleming',
  },
  {
    id: 6,
    question: 'Which river is the longest in the world?',
    options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
    correctAnswer: 'Nile',
  },
  {
    id: 7,
    question: 'Which gas is most abundant in Earth’s atmosphere?',
    options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'],
    correctAnswer: 'Nitrogen',
  },
  {
    id: 8,
    question: 'Which is the largest desert in the world?',
    options: ['Sahara', 'Arctic', 'Gobi', 'Antarctic'],
    correctAnswer: 'Antarctic',
  },
  {
    id: 9,
    question: 'Which element has the atomic number 1?',
    options: ['Oxygen', 'Hydrogen', 'Helium', 'Lithium'],
    correctAnswer: 'Hydrogen',
  },
  {
    id: 10,
    question: 'In which year did Pakistan win its first Cricket World Cup?',
    options: ['1987', '1992', '1996', '1999'],
    correctAnswer: '1992',
  },
  {
    id: 11,
    question: 'What is the currency of Japan?',
    options: ['Yuan', 'Yen', 'Won', 'Dollar'],
    correctAnswer: 'Yen',
  },
  {
    id: 12,
    question: 'Who painted the famous artwork "The Starry Night"?',
    options: [
      'Vincent van Gogh',
      'Pablo Picasso',
      'Leonardo da Vinci',
      'Claude Monet',
    ],
    correctAnswer: 'Vincent van Gogh',
  },
  {
    id: 13,
    question: 'Which country has the most natural lakes?',
    options: ['Canada', 'Russia', 'India', 'Brazil'],
    correctAnswer: 'Canada',
  },
  {
    id: 14,
    question:
      'What is the name of the first artificial satellite sent into space?',
    options: ['Sputnik 1', 'Apollo 11', 'Voyager 1', 'Hubble'],
    correctAnswer: 'Sputnik 1',
  },
  {
    id: 15,
    question: 'Who wrote the national anthem of Pakistan?',
    options: [
      'Faiz Ahmed Faiz',
      'Hafeez Jullundhri',
      'Allama Iqbal',
      'Ahmed Faraz',
    ],
    correctAnswer: 'Hafeez Jullundhri',
  },
  {
    id: 16,
    question: 'Which country is famous for the Great Barrier Reef?',
    options: ['Australia', 'New Zealand', 'South Africa', 'Canada'],
    correctAnswer: 'Australia',
  },
  {
    id: 17,
    question: 'What is the approximate age of the Earth?',
    options: [
      '3.5 billion years',
      '4.5 billion years',
      '5.5 billion years',
      '6.5 billion years',
    ],
    correctAnswer: '4.5 billion years',
  },
  {
    id: 18,
    question: 'Which is the highest mountain in the world?',
    options: ['K2', 'Mount Everest', 'Kangchenjunga', 'Lhotse'],
    correctAnswer: 'Mount Everest',
  },
  {
    id: 19,
    question: 'What is the hardest natural substance on Earth?',
    options: ['Gold', 'Iron', 'Diamond', 'Platinum'],
    correctAnswer: 'Diamond',
  },
  {
    id: 20,
    question: 'Which continent has the highest number of countries?',
    options: ['Asia', 'Africa', 'Europe', 'South America'],
    correctAnswer: 'Africa',
  },
  {
    id: 21,
    question: 'What is the longest river in South America?',
    options: [
      'Amazon River',
      'Mississippi River',
      'Yangtze River',
      'Ganges River',
    ],
    correctAnswer: 'Amazon River',
  },
  {
    id: 22,
    question:
      'Which element is essential for the production of thyroid hormones?',
    options: ['Iodine', 'Iron', 'Calcium', 'Potassium'],
    correctAnswer: 'Iodine',
  },
  {
    id: 23,
    question: 'Which country is the largest producer of coffee?',
    options: ['Vietnam', 'Brazil', 'Colombia', 'Ethiopia'],
    correctAnswer: 'Brazil',
  },
  {
    id: 24,
    question: 'In which year was the first iPhone released?',
    options: ['2005', '2006', '2007', '2008'],
    correctAnswer: '2007',
  },
  {
    id: 25,
    question: 'Which element is most abundant in the Earth’s crust?',
    options: ['Oxygen', 'Silicon', 'Aluminum', 'Iron'],
    correctAnswer: 'Oxygen',
  },
  {
    id: 26,
    question: 'Who developed the theory of evolution?',
    options: [
      'Isaac Newton',
      'Albert Einstein',
      'Charles Darwin',
      'Gregor Mendel',
    ],
    correctAnswer: 'Charles Darwin',
  },
  {
    id: 27,
    question: 'Which is the deepest ocean in the world?',
    options: [
      'Atlantic Ocean',
      'Indian Ocean',
      'Arctic Ocean',
      'Pacific Ocean',
    ],
    correctAnswer: 'Pacific Ocean',
  },
  {
    id: 28,
    question: 'What is the official language of Brazil?',
    options: ['Spanish', 'Portuguese', 'French', 'Italian'],
    correctAnswer: 'Portuguese',
  },
  {
    id: 29,
    question: 'Which planet has the most moons?',
    options: ['Earth', 'Mars', 'Saturn', 'Jupiter'],
    correctAnswer: 'Saturn',
  },
  {
    id: 30,
    question: 'Who was the first man to step on the Moon?',
    options: [
      'Neil Armstrong',
      'Buzz Aldrin',
      'Yuri Gagarin',
      'Michael Collins',
    ],
    correctAnswer: 'Neil Armstrong',
  },
  {
    id: 31,
    question: 'Which of these animals is a marsupial?',
    options: ['Koala', 'Elephant', 'Lion', 'Horse'],
    correctAnswer: 'Koala',
  },
  {
    id: 32,
    question: 'What is the largest island in the world?',
    options: ['Australia', 'Greenland', 'New Guinea', 'Borneo'],
    correctAnswer: 'Greenland',
  },
  {
    id: 33,
    question: 'What is the first element on the periodic table?',
    options: ['Hydrogen', 'Helium', 'Lithium', 'Carbon'],
    correctAnswer: 'Hydrogen',
  },
  {
    id: 34,
    question: 'What is the main ingredient of traditional Japanese miso soup?',
    options: ['Rice', 'Soybean', 'Tofu', 'Fish'],
    correctAnswer: 'Soybean',
  },
  {
    id: 35,
    question: 'Which country is home to the Great Pyramid of Giza?',
    options: ['Egypt', 'Iraq', 'Iran', 'India'],
    correctAnswer: 'Egypt',
  },
  {
    id: 36,
    question: 'Which gas is primarily responsible for global warming?',
    options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Methane'],
    correctAnswer: 'Carbon Dioxide',
  },
  {
    id: 37,
    question: 'What is the capital of Canada?',
    options: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    correctAnswer: 'Ottawa',
  },
  {
    id: 38,
    question: 'Who invented the telephone?',
    options: [
      'Thomas Edison',
      'Alexander Graham Bell',
      'Nikola Tesla',
      'Michael Faraday',
    ],
    correctAnswer: 'Alexander Graham Bell',
  },
  {
    id: 39,
    question: 'Which country was the first to send a human into space?',
    options: ['USA', 'Russia', 'China', 'Germany'],
    correctAnswer: 'Russia',
  },
  {
    id: 40,
    question: 'Which planet is known as the Red Planet?',
    options: ['Venus', 'Earth', 'Mars', 'Jupiter'],
    correctAnswer: 'Mars',
  },
  {
    id: 41,
    question: 'Which city is known as the Big Apple?',
    options: ['Los Angeles', 'Chicago', 'New York City', 'San Francisco'],
    correctAnswer: 'New York City',
  },
  {
    id: 42,
    question: 'What is the fastest land animal?',
    options: ['Lion', 'Elephant', 'Cheetah', 'Horse'],
    correctAnswer: 'Cheetah',
  },
  {
    id: 43,
    question: 'Who was the first president of the United States?',
    options: [
      'Thomas Jefferson',
      'Abraham Lincoln',
      'George Washington',
      'John Adams',
    ],
    correctAnswer: 'George Washington',
  },
  {
    id: 44,
    question: 'Which ocean is the largest?',
    options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    correctAnswer: 'Pacific',
  },
  {
    id: 45,
    question: 'Which country is known as the Land of the Midnight Sun?',
    options: ['Norway', 'Sweden', 'Finland', 'Iceland'],
    correctAnswer: 'Norway',
  },
  {
    id: 46,
    question: 'Which element is the main component of natural gas?',
    options: ['Carbon', 'Hydrogen', 'Methane', 'Oxygen'],
    correctAnswer: 'Methane',
  },
  {
    id: 47,
    question: 'What is the smallest bone in the human body?',
    options: ['Stapes', 'Femur', 'Radius', 'Tibia'],
    correctAnswer: 'Stapes',
  },
  {
    id: 48,
    question: 'Which planet is closest to the Sun?',
    options: ['Venus', 'Earth', 'Mercury', 'Mars'],
    correctAnswer: 'Mercury',
  },
  {
    id: 49,
    question: 'Which country is the largest producer of oil?',
    options: ['USA', 'Russia', 'Saudi Arabia', 'China'],
    correctAnswer: 'USA',
  },
  {
    id: 50,
    question: 'Who is the author of the "Harry Potter" series?',
    options: [
      'J.R.R. Tolkien',
      'J.K. Rowling',
      'George R.R. Martin',
      'Suzanne Collins',
    ],
    correctAnswer: 'J.K. Rowling',
  },
  {
    id: 51,
    question: 'Which of these animals is a marsupial?',
    options: ['Koala', 'Elephant', 'Lion', 'Horse'],
    correctAnswer: 'Koala',
  },
  {
    id: 52,
    question: 'What is the largest island in the world?',
    options: ['Australia', 'Greenland', 'New Guinea', 'Borneo'],
    correctAnswer: 'Greenland',
  },
  {
    id: 53,
    question: 'What is the first element on the periodic table?',
    options: ['Hydrogen', 'Helium', 'Lithium', 'Carbon'],
    correctAnswer: 'Hydrogen',
  },
  {
    id: 54,
    question: 'What is the main ingredient of traditional Japanese miso soup?',
    options: ['Rice', 'Soybean', 'Tofu', 'Fish'],
    correctAnswer: 'Soybean',
  },
  {
    id: 55,
    question: 'Which country is home to the Great Pyramid of Giza?',
    options: ['Egypt', 'Iraq', 'Iran', 'India'],
    correctAnswer: 'Egypt',
  },
  {
    id: 56,
    question: 'Which gas is primarily responsible for global warming?',
    options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Methane'],
    correctAnswer: 'Carbon Dioxide',
  },
  {
    id: 57,
    question: 'What is the capital of Canada?',
    options: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    correctAnswer: 'Ottawa',
  },
  {
    id: 58,
    question: 'Who invented the telephone?',
    options: [
      'Thomas Edison',
      'Alexander Graham Bell',
      'Nikola Tesla',
      'Michael Faraday',
    ],
    correctAnswer: 'Alexander Graham Bell',
  },
  {
    id: 59,
    question: 'Which country was the first to send a human into space?',
    options: ['USA', 'Russia', 'China', 'Germany'],
    correctAnswer: 'Russia',
  },
  {
    id: 60,
    question: 'Which planet is known as the Red Planet?',
    options: ['Venus', 'Earth', 'Mars', 'Jupiter'],
    correctAnswer: 'Mars',
  },
  {
    id: 61,
    question: 'Which city is known as the Big Apple?',
    options: ['Los Angeles', 'Chicago', 'New York City', 'San Francisco'],
    correctAnswer: 'New York City',
  },
  {
    id: 62,
    question: 'What is the fastest land animal?',
    options: ['Lion', 'Elephant', 'Cheetah', 'Horse'],
    correctAnswer: 'Cheetah',
  },
  {
    id: 63,
    question: 'Who was the first president of the United States?',
    options: [
      'Thomas Jefferson',
      'Abraham Lincoln',
      'George Washington',
      'John Adams',
    ],
    correctAnswer: 'George Washington',
  },
  {
    id: 64,
    question: 'Which ocean is the largest?',
    options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    correctAnswer: 'Pacific',
  },
  {
    id: 65,
    question: 'Which country is known as the Land of the Midnight Sun?',
    options: ['Norway', 'Sweden', 'Finland', 'Iceland'],
    correctAnswer: 'Norway',
  },
  {
    id: 66,
    question: 'Which element is the main component of natural gas?',
    options: ['Carbon', 'Hydrogen', 'Methane', 'Oxygen'],
    correctAnswer: 'Methane',
  },
  {
    id: 67,
    question: 'What is the smallest bone in the human body?',
    options: ['Stapes', 'Femur', 'Radius', 'Tibia'],
    correctAnswer: 'Stapes',
  },
  {
    id: 68,
    question: 'Which planet is closest to the Sun?',
    options: ['Venus', 'Earth', 'Mercury', 'Mars'],
    correctAnswer: 'Mercury',
  },
  {
    id: 69,
    question: 'Which country is the largest producer of oil?',
    options: ['USA', 'Russia', 'Saudi Arabia', 'China'],
    correctAnswer: 'USA',
  },
  {
    id: 70,
    question: 'Who is the author of the "Harry Potter" series?',
    options: [
      'J.R.R. Tolkien',
      'J.K. Rowling',
      'George R.R. Martin',
      'Suzanne Collins',
    ],
    correctAnswer: 'J.K. Rowling',
  },
];

export const hardQuestions = [
  {
    id: 1,
    question: 'Which country is known as the "Land of the Rising Sun"?',
    options: ['China', 'Japan', 'Thailand', 'South Korea'],
    correctAnswer: 'Japan',
  },
  {
    id: 2,
    question: 'Who developed the theory of relativity?',
    options: [
      'Isaac Newton',
      'Albert Einstein',
      'Galileo Galilei',
      'Niels Bohr',
    ],
    correctAnswer: 'Albert Einstein',
  },
  {
    id: 3,
    question: 'Which element is most abundant in the Earth’s crust?',
    options: ['Oxygen', 'Silicon', 'Aluminum', 'Iron'],
    correctAnswer: 'Oxygen',
  },
  {
    id: 4,
    question: 'What is the chemical formula for water?',
    options: ['H2O', 'CO2', 'O2', 'H2SO4'],
    correctAnswer: 'H2O',
  },
  {
    id: 5,
    question: 'In which year did Pakistan gain independence?',
    options: ['1947', '1945', '1950', '1960'],
    correctAnswer: '1947',
  },
  {
    id: 6,
    question: 'What is the largest planet in our solar system?',
    options: ['Earth', 'Jupiter', 'Saturn', 'Neptune'],
    correctAnswer: 'Jupiter',
  },
  {
    id: 7,
    question: 'Who is the author of the book "1984"?',
    options: [
      'George Orwell',
      'Aldous Huxley',
      'J.K. Rowling',
      'F. Scott Fitzgerald',
    ],
    correctAnswer: 'George Orwell',
  },
  {
    id: 8,
    question: 'Which ocean is the largest?',
    options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    correctAnswer: 'Pacific',
  },
  {
    id: 9,
    question: 'Which country is home to the Great Barrier Reef?',
    options: ['Australia', 'New Zealand', 'South Africa', 'Brazil'],
    correctAnswer: 'Australia',
  },
  {
    id: 10,
    question: 'Which planet is known as the "Red Planet"?',
    options: ['Mars', 'Venus', 'Earth', 'Jupiter'],
    correctAnswer: 'Mars',
  },
  {
    id: 11,
    question: 'What is the capital city of France?',
    options: ['Berlin', 'Madrid', 'Paris', 'Rome'],
    correctAnswer: 'Paris',
  },
  {
    id: 12,
    question: 'Who invented the telephone?',
    options: [
      'Nikola Tesla',
      'Michael Faraday',
      'Alexander Graham Bell',
      'Thomas Edison',
    ],
    correctAnswer: 'Alexander Graham Bell',
  },
  {
    id: 13,
    question: 'Which country is the largest producer of coffee?',
    options: ['Brazil', 'Vietnam', 'Colombia', 'India'],
    correctAnswer: 'Brazil',
  },
  {
    id: 14,
    question: 'What is the main ingredient in traditional Japanese sushi?',
    options: ['Rice', 'Fish', 'Seaweed', 'Soy Sauce'],
    correctAnswer: 'Rice',
  },
  {
    id: 15,
    question: 'Who painted the "Mona Lisa"?',
    options: [
      'Pablo Picasso',
      'Vincent van Gogh',
      'Leonardo da Vinci',
      'Claude Monet',
    ],
    correctAnswer: 'Leonardo da Vinci',
  },
  {
    id: 16,
    question: 'Which is the tallest mountain in the world?',
    options: ['Mount Everest', 'K2', 'Kangchenjunga', 'Lhotse'],
    correctAnswer: 'Mount Everest',
  },
  {
    id: 17,
    question: 'Which gas makes up most of the Earth’s atmosphere?',
    options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'],
    correctAnswer: 'Nitrogen',
  },
  {
    id: 18,
    question: 'What is the smallest bone in the human body?',
    options: ['Stapes', 'Femur', 'Radius', 'Clavicle'],
    correctAnswer: 'Stapes',
  },
  {
    id: 19,
    question: 'Who was the first person to set foot on the Moon?',
    options: [
      'Buzz Aldrin',
      'Neil Armstrong',
      'Michael Collins',
      'Yuri Gagarin',
    ],
    correctAnswer: 'Neil Armstrong',
  },
  {
    id: 20,
    question: 'Which country is home to the Sahara Desert?',
    options: ['Egypt', 'Saudi Arabia', 'Sudan', 'Morocco'],
    correctAnswer: 'Egypt',
  },
  {
    id: 21,
    question: 'What is the hardest natural substance on Earth?',
    options: ['Gold', 'Iron', 'Diamond', 'Platinum'],
    correctAnswer: 'Diamond',
  },
  {
    id: 22,
    question: 'Which is the longest river in the world?',
    options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
    correctAnswer: 'Nile',
  },
  {
    id: 23,
    question: 'What is the square root of 144?',
    options: ['12', '14', '16', '18'],
    correctAnswer: '12',
  },
  {
    id: 24,
    question: 'Which continent has the most countries?',
    options: ['Asia', 'Africa', 'Europe', 'South America'],
    correctAnswer: 'Africa',
  },
  {
    id: 25,
    question: 'What is the capital of Canada?',
    options: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    correctAnswer: 'Ottawa',
  },
  {
    id: 26,
    question: 'What is the largest desert in the world?',
    options: ['Sahara', 'Gobi', 'Kalahari', 'Antarctic'],
    correctAnswer: 'Antarctic',
  },
  {
    id: 27,
    question: 'Who discovered penicillin?',
    options: [
      'Marie Curie',
      'Isaac Newton',
      'Louis Pasteur',
      'Alexander Fleming',
    ],
    correctAnswer: 'Alexander Fleming',
  },
  {
    id: 28,
    question: 'Which country is the largest producer of oil?',
    options: ['Saudi Arabia', 'USA', 'Russia', 'China'],
    correctAnswer: 'USA',
  },
  {
    id: 29,
    question: 'Who was the first president of the United States?',
    options: [
      'Abraham Lincoln',
      'George Washington',
      'Thomas Jefferson',
      'John Adams',
    ],
    correctAnswer: 'George Washington',
  },
  {
    id: 30,
    question: 'What is the official language of Brazil?',
    options: ['Spanish', 'Portuguese', 'Italian', 'French'],
    correctAnswer: 'Portuguese',
  },
  {
    id: 31,
    question: 'Which animal is known as the "King of the Jungle"?',
    options: ['Lion', 'Elephant', 'Tiger', 'Giraffe'],
    correctAnswer: 'Lion',
  },
  {
    id: 32,
    question: 'Which scientist is famous for his theory of evolution?',
    options: [
      'Isaac Newton',
      'Charles Darwin',
      'Galileo Galilei',
      'Albert Einstein',
    ],
    correctAnswer: 'Charles Darwin',
  },
  {
    id: 33,
    question: 'Which element has the atomic number 1?',
    options: ['Hydrogen', 'Oxygen', 'Helium', 'Carbon'],
    correctAnswer: 'Hydrogen',
  },
  {
    id: 34,
    question: 'Which planet is closest to the Sun?',
    options: ['Earth', 'Venus', 'Mercury', 'Mars'],
    correctAnswer: 'Mercury',
  },
  {
    id: 35,
    question: 'What is the longest-running TV show?',
    options: ['The Simpsons', 'Friends', 'The Office', 'Law & Order'],
    correctAnswer: 'The Simpsons',
  },
  {
    id: 36,
    question: 'What is the largest island in the world?',
    options: ['Australia', 'Greenland', 'New Guinea', 'Borneo'],
    correctAnswer: 'Greenland',
  },
  {
    id: 37,
    question: 'What is the capital of Japan?',
    options: ['Seoul', 'Tokyo', 'Beijing', 'Osaka'],
    correctAnswer: 'Tokyo',
  },
  {
    id: 38,
    question: 'Which country has the most time zones?',
    options: ['Russia', 'USA', 'Canada', 'Australia'],
    correctAnswer: 'Russia',
  },
  {
    id: 39,
    question: 'Which planet has the most moons?',
    options: ['Earth', 'Jupiter', 'Saturn', 'Mars'],
    correctAnswer: 'Saturn',
  },
  {
    id: 40,
    question: 'Which is the largest continent by land area?',
    options: ['Africa', 'Asia', 'North America', 'Europe'],
    correctAnswer: 'Asia',
  },
  {
    id: 41,
    question: 'Who invented the light bulb?',
    options: [
      'Nikola Tesla',
      'Thomas Edison',
      'Alexander Graham Bell',

      'Benjamin Franklin',
    ],
    correctAnswer: 'Thomas Edison',
  },
  {
    id: 42,
    question: 'What is the hardest known metal?',
    options: ['Iron', 'Gold', 'Platinum', 'Tungsten'],
    correctAnswer: 'Tungsten',
  },
  {
    id: 43,
    question: 'Which country is the world’s largest producer of cocoa?',
    options: ['Brazil', 'Ghana', 'Nigeria', 'Ivory Coast'],
    correctAnswer: 'Ivory Coast',
  },
  {
    id: 44,
    question: 'Which country has the longest coastline?',
    options: ['USA', 'Australia', 'Canada', 'Russia'],
    correctAnswer: 'Canada',
  },
  {
    id: 45,
    question: 'Who was the first woman to win a Nobel Prize?',
    options: [
      'Marie Curie',
      'Rosalind Franklin',
      'Barbara McClintock',
      'Dorothy Hodgkin',
    ],
    correctAnswer: 'Marie Curie',
  },
  {
    id: 46,
    question: 'What is the currency of Japan?',
    options: ['Yuan', 'Won', 'Yen', 'Ringgit'],
    correctAnswer: 'Yen',
  },
  {
    id: 47,
    question: 'Who was the first human to journey into outer space?',
    options: [
      'Neil Armstrong',
      'Yuri Gagarin',
      'Buzz Aldrin',
      'Valentina Tereshkova',
    ],
    correctAnswer: 'Yuri Gagarin',
  },
  {
    id: 48,
    question: 'Which country was formerly known as Ceylon?',
    options: ['Sri Lanka', 'Bangladesh', 'Maldives', 'Nepal'],
    correctAnswer: 'Sri Lanka',
  },
  {
    id: 49,
    question: 'Who discovered America?',
    options: [
      'Christopher Columbus',
      'Marco Polo',
      'Vasco da Gama',
      'Ferdinand Magellan',
    ],
    correctAnswer: 'Christopher Columbus',
  },
  {
    id: 50,
    question: 'Which country is famous for the Great Wall?',
    options: ['Japan', 'India', 'China', 'Korea'],
    correctAnswer: 'China',
  },
  {
    id: 51,
    question: 'Which country is known for the Taj Mahal?',
    options: ['Pakistan', 'Bangladesh', 'India', 'Nepal'],
    correctAnswer: 'India',
  },
  {
    id: 52,
    question: 'Which city is known as the Big Apple?',
    options: ['Los Angeles', 'Chicago', 'New York City', 'San Francisco'],
    correctAnswer: 'New York City',
  },
  {
    id: 53,
    question: 'Who is the author of the "Harry Potter" series?',
    options: [
      'J.R.R. Tolkien',
      'J.K. Rowling',
      'George R.R. Martin',
      'Suzanne Collins',
    ],
    correctAnswer: 'J.K. Rowling',
  },
  {
    id: 54,
    question: 'What is the capital city of Australia?',
    options: ['Melbourne', 'Sydney', 'Brisbane', 'Canberra'],
    correctAnswer: 'Canberra',
  },
  {
    id: 55,
    question: 'What is the largest country in the world by area?',
    options: ['USA', 'China', 'Canada', 'Russia'],
    correctAnswer: 'Russia',
  },
  {
    id: 56,
    question: 'Which company is the largest tech company by revenue?',
    options: ['Microsoft', 'Apple', 'Amazon', 'Google'],
    correctAnswer: 'Apple',
  },
  {
    id: 57,
    question: 'What is the capital of Egypt?',
    options: ['Cairo', 'Alexandria', 'Giza', 'Luxor'],
    correctAnswer: 'Cairo',
  },
  {
    id: 58,
    question: 'Who is known as the "Father of Computers"?',
    options: ['Charles Babbage', 'Alan Turing', 'Bill Gates', 'Steve Jobs'],
    correctAnswer: 'Charles Babbage',
  },
  {
    id: 59,
    question: 'What does the "HTTP" in website URLs stand for?',
    options: [
      'HyperText Transport Protocol',
      'HyperText Transfer Protocol',
      'HyperText Telecommunication Protocol',
      'HyperText Transcription Protocol',
    ],
    correctAnswer: 'HyperText Transfer Protocol',
  },
  {
    id: 60,
    question: 'Which country invented paper?',
    options: ['China', 'Egypt', 'Greece', 'India'],
    correctAnswer: 'China',
  },
  {
    id: 61,
    question: 'Who is known for discovering the structure of DNA?',
    options: [
      'James Watson',
      'Francis Crick',
      'Rosalind Franklin',
      'Gregor Mendel',
    ],
    correctAnswer: 'James Watson',
  },
  {
    id: 62,
    question: 'What is the longest river in Asia?',
    options: ['Ganges', 'Yangtze', 'Mekong', 'Amur'],
    correctAnswer: 'Yangtze',
  },
  {
    id: 63,
    question: 'Who wrote "The Iliad"?',
    options: ['Homer', 'Sophocles', 'Virgil', 'Aristotle'],
    correctAnswer: 'Homer',
  },
  {
    id: 64,
    question: 'Which planet is known as the "Morning Star"?',
    options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
    correctAnswer: 'Venus',
  },
  {
    id: 65,
    question: 'Which country has the largest population in the world?',
    options: ['India', 'USA', 'China', 'Indonesia'],
    correctAnswer: 'China',
  },
  {
    id: 66,
    question: 'Who was the first woman to fly solo across the Atlantic Ocean?',
    options: [
      'Amelia Earhart',
      'Bessie Coleman',
      'Harriet Quimby',
      'Jacqueline Cochran',
    ],
    correctAnswer: 'Amelia Earhart',
  },
  {
    id: 67,
    question: 'Which is the most common blood type in the world?',
    options: ['A+', 'O+', 'B+', 'AB+'],
    correctAnswer: 'O+',
  },
  {
    id: 68,
    question: 'What is the official language of Switzerland?',
    options: ['German', 'French', 'Italian', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 69,
    question: 'Which planet is named after the Roman god of war?',
    options: ['Mars', 'Venus', 'Jupiter', 'Saturn'],
    correctAnswer: 'Mars',
  },
  {
    id: 70,
    question: 'What is the longest-living animal?',
    options: ['Tortoise', 'Whale', 'Shark', 'Elephant'],
    correctAnswer: 'Tortoise',
  },
  {
    id: 71,
    question: 'Who discovered America?',
    options: [
      'Christopher Columbus',
      'Marco Polo',
      'Vasco da Gama',
      'Ferdinand Magellan',
    ],
    correctAnswer: 'Christopher Columbus',
  },
  {
    id: 72,
    question: 'Which country is known as the "Land of the Midnight Sun"?',
    options: ['Norway', 'Sweden', 'Finland', 'Iceland'],
    correctAnswer: 'Norway',
  },
  {
    id: 73,
    question: 'Which country is known as the "Emerald Isle"?',
    options: ['Ireland', 'Scotland', 'Wales', 'New Zealand'],
    correctAnswer: 'Ireland',
  },
  {
    id: 74,
    question: 'Who is known for the discovery of the theory of gravity?',
    options: [
      'Isaac Newton',
      'Albert Einstein',
      'Nikola Tesla',
      'Galileo Galilei',
    ],
    correctAnswer: 'Isaac Newton',
  },
  {
    id: 75,
    question: 'What is the capital of Argentina?',
    options: ['Buenos Aires', 'Santiago', 'Lima', 'Bogotá'],
    correctAnswer: 'Buenos Aires',
  },
  {
    id: 76,
    question: 'Which chemical element is represented by the symbol "Na"?',
    options: ['Sodium', 'Nitrogen', 'Nickel', 'Neon'],
    correctAnswer: 'Sodium',
  },
  {
    id: 77,
    question: 'Which is the smallest country in the world?',
    options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
    correctAnswer: 'Vatican City',
  },
  {
    id: 78,
    question: 'What is the fastest land animal?',
    options: ['Cheetah', 'Lion', 'Elephant', 'Gazelle'],
    correctAnswer: 'Cheetah',
  },
  {
    id: 79,
    question: 'What is the official language of Brazil?',
    options: ['Spanish', 'Portuguese', 'Italian', 'French'],
    correctAnswer: 'Portuguese',
  },
  {
    id: 80,
    question: 'What year did World War I begin?',
    options: ['1914', '1912', '1920', '1939'],
    correctAnswer: '1914',
  },
  {
    id: 81,
    question: 'What is the capital of Italy?',

    options: ['Rome', 'Venice', 'Florence', 'Milan'],
    correctAnswer: 'Rome',
  },
  {
    id: 82,
    question: 'Which is the largest desert in the world?',
    options: ['Sahara', 'Arabian', 'Gobi', 'Kalahari'],
    correctAnswer: 'Sahara',
  },
  {
    id: 83,
    question: "What is the most common gas in the Earth's atmosphere?",
    options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'],
    correctAnswer: 'Nitrogen',
  },
  {
    id: 84,
    question: 'Which country is the largest producer of coffee?',
    options: ['Brazil', 'Vietnam', 'Colombia', 'Ethiopia'],
    correctAnswer: 'Brazil',
  },
  {
    id: 85,
    question: 'Who invented the telephone?',
    options: [
      'Thomas Edison',
      'Nikola Tesla',
      'Alexander Graham Bell',
      'Michael Faraday',
    ],
    correctAnswer: 'Alexander Graham Bell',
  },
  {
    id: 86,
    question:
      'Which element is essential for the formation of bones and teeth?',
    options: ['Calcium', 'Iron', 'Magnesium', 'Phosphorus'],
    correctAnswer: 'Calcium',
  },
  {
    id: 87,
    question: 'Which country is known for the Eiffel Tower?',
    options: ['Germany', 'France', 'Italy', 'Spain'],
    correctAnswer: 'France',
  },
  {
    id: 88,
    question: 'Who invented the light bulb?',
    options: [
      'Alexander Graham Bell',
      'Thomas Edison',
      'Nikola Tesla',
      'James Watt',
    ],
    correctAnswer: 'Thomas Edison',
  },
  {
    id: 89,
    question: 'Which is the longest mountain range in the world?',
    options: ['Himalayas', 'Andes', 'Rockies', 'Alps'],
    correctAnswer: 'Andes',
  },
  {
    id: 90,
    question: 'Who wrote "Pride and Prejudice"?',
    options: [
      'Charlotte Brontë',
      'Emily Dickinson',
      'Jane Austen',
      'Virginia Woolf',
    ],
    correctAnswer: 'Jane Austen',
  },
  {
    id: 91,
    question: 'Which country is the largest producer of natural gas?',
    options: ['USA', 'Russia', 'Canada', 'Iran'],
    correctAnswer: 'USA',
  },
  {
    id: 92,
    question: 'What is the square root of 64?',
    options: ['6', '7', '8', '9'],
    correctAnswer: '8',
  },
  {
    id: 93,
    question: 'What is the chemical symbol for gold?',
    options: ['Ag', 'Au', 'Pb', 'Fe'],
    correctAnswer: 'Au',
  },
  {
    id: 94,
    question: 'Who was the first woman to win a Nobel Prize in Chemistry?',
    options: [
      'Marie Curie',
      'Dorothy Crowfoot Hodgkin',
      'Rosalind Franklin',
      'Madame Curie',
    ],
    correctAnswer: 'Marie Curie',
  },
  {
    id: 95,
    question: 'Which country is known for the Great Barrier Reef?',
    options: ['USA', 'Australia', 'New Zealand', 'Indonesia'],
    correctAnswer: 'Australia',
  },
  {
    id: 96,
    question: 'What is the hardest known natural substance?',
    options: ['Diamond', 'Graphene', 'Iron', 'Gold'],
    correctAnswer: 'Diamond',
  },
  {
    id: 97,
    question: 'What is the capital of Canada?',
    options: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'],
    correctAnswer: 'Ottawa',
  },
  {
    id: 98,
    question: 'Who painted the Mona Lisa?',
    options: [
      'Pablo Picasso',
      'Vincent van Gogh',
      'Claude Monet',
      'Leonardo da Vinci',
    ],
    correctAnswer: 'Leonardo da Vinci',
  },
  {
    id: 99,
    question: 'Which chemical element is represented by the symbol "O"?',
    options: ['Oxygen', 'Osmium', 'Opium', 'Ozone'],
    correctAnswer: 'Oxygen',
  },
  {
    id: 100,
    question: 'What is the tallest mountain in the world?',
    options: ['K2', 'Mount Kilimanjaro', 'Mount Everest', 'Mount Fuji'],
    correctAnswer: 'Mount Everest',
  },
];
